[versions]

camerak = "0.0.12"
faceDetection = "16.1.7"
hazeMaterials = "1.6.4"
koinAnnotationsBom = "2.0.1-RC1"
koinBom = "4.1.0"
kotlin = "2.2.0-RC2"
compose = "1.8.1"
agp = "8.10.1"
androidx-activityCompose = "1.11.0-rc01"
androidx-uiTest = "1.8.1"
kermit = "2.0.5"
kotlinx-coroutines = "1.10.2"
ktor = "3.1.3"
androidx-lifecycle = "2.9.0"
androidx-navigation = "2.9.0-beta02"
kotlinx-serialization = "1.8.1"
coil = "3.2.0"
multiplatformSettings = "1.3.0"
kotlinx-datetime = "0.6.2"
ksp = "2.2.0-RC2-2.0.2"
buildConfig = "5.6.5"
materialKolor = "3.0.0-beta05"
hotReload = "1.0.0-alpha10"
composeIcons = "1.1.1"
permission = "0.12.2"
supabase = "3.1.4"
compass = "1.2.2"
adaptive = "1.1.2"

[libraries]

camerak = { module = "io.github.kashif-mehmood-km:camerak", version.ref = "camerak" }
compose-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "adaptive" }
android-faceDetection = { module = "com.google.mlkit:face-detection", version.ref = "faceDetection" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "hazeMaterials" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "hazeMaterials" }
materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-uitest-testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-uiTest" }
androidx-uitest-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-uiTest" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
koin-annotations-bom = { module = "io.insert-koin:koin-annotations-bom", version.ref = "koinAnnotationsBom" }
koin-annotations = { module = "io.insert-koin:koin-annotations" }
koin-annotations-ksp = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koinAnnotationsBom" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-compose = { module = "io.insert-koin:koin-compose" }
composeIcons-lineAwesome = { module = "br.com.devsrsouza.compose.icons:line-awesome", version.ref = "composeIcons" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-curl = { module = "io.ktor:ktor-client-curl", version.ref = "ktor" }
ktor-client-winhttp = { module = "io.ktor:ktor-client-winhttp", version.ref = "ktor" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
coil = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
permission = { module = "tech.kotlinlang:permission", version.ref = "permission" }
supabase-bom = { group = "io.github.jan-tennert.supabase", name = "bom", version.ref = "supabase" }
supabase-auth = { group = "io.github.jan-tennert.supabase", name = "auth-kt" }
supabase-imageLoader = { group = "io.github.jan-tennert.supabase", name = "imageloader-integration" }
supabase-postgrest = { group = "io.github.jan-tennert.supabase", name = "postgrest-kt" }
supabase-composeAuth = { group = "io.github.jan-tennert.supabase", name = "compose-auth" }
supabase-storage = { group = "io.github.jan-tennert.supabase", name = "storage-kt" }
supabase-function = { group = "io.github.jan-tennert.supabase", name = "functions-kt" }
supabase-coil = { group = "io.github.jan-tennert.supabase", name = "coil3-integration" }

android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradlePlugin = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "compose" }
ksp-gradlePlugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }


multiplatformSettings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
multiplatformSettings-noArgs = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformSettings" }
multiplatformSettings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatformSettings" }

compass-geolocation = { module = "dev.jordond.compass:geolocation", version.ref = "compass" }
compass-permissions-mobile = { module = "dev.jordond.compass:permissions-mobile", version.ref = "compass" }
compass-geolocation-mobile = { module = "dev.jordond.compass:geolocation-mobile", version.ref = "compass" }


[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "hotReload"}
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }

[bundles]
supabase = [
    "supabase-auth",
    "supabase-postgrest",
    #    "supabase-storage",
    #    "supabase-composeAuth",
    #    "supabase-coil",
    "supabase-function"
]