[versions]

camerak = "0.1.0"
faceDetection = "16.1.7"
hazeMaterials = "2.0.0"
inspektor = "1.2.5"
room = "2.8.4"
koinAnnotationsBom = "2.3.1"
koinBom = "4.1.1"
kotlin = "2.3.0"
compose = "1.10.0"
agp = "8.10.1"
androidx-activityCompose = "1.12.2"
androidx-uiTest = "1.10.0"
kermit = "2.0.8"
kotlinx-coroutines = "1.10.2"
ktor = "3.4.0"
ktorfit = "2.4.0"
androidx-lifecycle = "2.9.6"
androidx-navigation = "2.9.1"
kotlinx-serialization = "1.10.0"
coil = "3.3.0"
multiplatformSettings = "1.3.0"
kotlinx-datetime = "0.7.1"
ksp = "2.3.0"
buildConfig = "6.0.7"
materialKolor = "4.1.0"
hotReload = "1.0.0"
composeIcons = "1.1.1"
permission = "0.12.2"
supabase = "3.3.0"
compass = "1.2.2"
adaptive = "1.1.2"
navigation3 = "1.1.0-alpha01"
navigation3Event = "1.0.0-rc02"
androidxNavigation3Material = "1.3.0-alpha03"
composeMediaPlayer = "0.8.7"

[libraries]

camerak = { module = "io.github.kashif-mehmood-km:camerak", version.ref = "camerak" }
compose-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "adaptive" }
android-faceDetection = { module = "com.google.mlkit:face-detection", version.ref = "faceDetection" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "hazeMaterials" }
haze-materials = { module = "dev.chrisbanes.haze:haze-materials", version.ref = "hazeMaterials" }
inspektor = { module = "io.github.orioneee:axer", version.ref = "inspektor" }
materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
composeMediaPlayer = { module = "io.github.kdroidfilter:composemediaplayer", version.ref = "composeMediaPlayer" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "navigation3" }
androidx-navigation3-event = { module = "org.jetbrains.androidx.navigationevent:navigationevent-compose", version.ref = "navigation3Event" }
androidx-navigation3-material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation3", version.ref = "androidxNavigation3Material" }
androidx-uitest-testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-uiTest" }
androidx-uitest-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-uiTest" }
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
koin-annotations-bom = { module = "io.insert-koin:koin-annotations-bom", version.ref = "koinAnnotationsBom" }
koin-annotations = { module = "io.insert-koin:koin-annotations" }
koin-annotations-ksp = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koinAnnotationsBom" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-compose = { module = "io.insert-koin:koin-compose" }
composeIcons-lineAwesome = { module = "br.com.devsrsouza.compose.icons:line-awesome", version.ref = "composeIcons" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-curl = { module = "io.ktor:ktor-client-curl", version.ref = "ktor" }
ktor-client-winhttp = { module = "io.ktor:ktor-client-winhttp", version.ref = "ktor" }
androidx-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
coil = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
permission = { module = "tech.kotlinlang:permission", version.ref = "permission" }
supabase-bom = { group = "io.github.jan-tennert.supabase", name = "bom", version.ref = "supabase" }
supabase-auth = { group = "io.github.jan-tennert.supabase", name = "auth-kt" }
supabase-imageLoader = { group = "io.github.jan-tennert.supabase", name = "imageloader-integration" }
supabase-postgrest = { group = "io.github.jan-tennert.supabase", name = "postgrest-kt" }
supabase-composeAuth = { group = "io.github.jan-tennert.supabase", name = "compose-auth" }
supabase-storage = { group = "io.github.jan-tennert.supabase", name = "storage-kt" }
supabase-function = { group = "io.github.jan-tennert.supabase", name = "functions-kt" }
supabase-coil = { group = "io.github.jan-tennert.supabase", name = "coil3-integration" }
ktorfit = { module = "de.jensklingenberg.ktorfit:ktorfit-lib", version.ref = "ktorfit" }
ktorfit-ksp = { module = "de.jensklingenberg.ktorfit:ktorfit-ksp", version.ref = "ktorfit" }
ktorfit-converter = { module = "de.jensklingenberg.ktorfit:ktorfit-converters-response", version.ref = "ktorfit" }
ktorfit-converter-call = { module = "de.jensklingenberg.ktorfit:ktorfit-converters-call", version.ref = "ktorfit" }
ktorfit-converter-flow = { module = "de.jensklingenberg.ktorfit:ktorfit-converters-flow", version.ref = "ktorfit" }

android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradlePlugin = { module = "org.jetbrains.compose:org.jetbrains.compose.gradle.plugin", version.ref = "compose" }
ksp-gradlePlugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
ktorfit-gradlePlugin = { module = "de.jensklingenberg.ktorfit:ktorfit-gradle-plugin", version.ref = "ktorfit" }
room-gradlePlugin = { module = "androidx.room:room-gradle-plugin", version.ref = "room" }


multiplatformSettings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
multiplatformSettings-noArgs = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformSettings" }
multiplatformSettings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatformSettings" }

compass-geolocation = { module = "dev.jordond.compass:geolocation", version.ref = "compass" }
compass-permissions-mobile = { module = "dev.jordond.compass:permissions-mobile", version.ref = "compass" }
compass-geolocation-mobile = { module = "dev.jordond.compass:geolocation-mobile", version.ref = "compass" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-sqlite = { module = "androidx.sqlite:sqlite-bundled", version = "2.6.2" }


[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "hotReload"}
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildConfig" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }
room = { id = "androidx.room", version.ref = "room" }

[bundles]
supabase = [
    "supabase-auth",
    "supabase-postgrest",
    #    "supabase-storage",
    #    "supabase-composeAuth",
    #    "supabase-coil",
    "supabase-function"
]